In [1]:
import numpy as np

# Your provided dataset
data_array = np.array([
    [1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.00],
    [1002, 206, 305, 4, 10.99, 5, 6, 'Online', 'Cash', np.nan, 41.75],
    [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', np.nan, 49.46],
    [1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0, 13.05],
    [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
    [1006, 208, 308, 1, 12.75, 0, 0, 'East', 'Cash', 502.0, 12.75],
    [1007, 206, 302, 3, 7.25, 0, 1, 'Online', 'PayPal', np.nan, 21.75],
    [1008, 206, 308, 1, 10.99, 5, 8, 'West', 'Credit Card', 503.0, 10.44],
    [1009, 204, 304, 5, 25.5, 0, 6, 'South', 'Credit Card', 501.0, 127.50],
    [1010, 210, 302, 3, 8.5, 0, 4, 'North', 'Debit Card', 503.0, 25.50],
    [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.50],
    [1012, 205, 301, 1, 10.99, 0, 1, 'West', 'Debit Card', 503.0, 10.99],
    [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0, 45.90],
    [1014, 202, 304, 1, 12.75, 5, 5, 'East', 'Cash', 501.0, 12.11],
    [1015, 208, 303, 5, 49.99, 5, 4, 'Online', 'Credit Card', np.nan, 237.41],
    [1016, 207, 301, 2, 10.99, 5, 5, 'West', 'Credit Card', 503.0, 20.88],
    [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78],
    [1018, 202, 302, 5, 49.99, 5, 8, 'North', 'Credit Card', 503.0, 237.41],
    [1019, 208, 304, 2, 7.25, 5, 7, 'South', 'Debit Card', 502.0, 13.78],
    [1020, 206, 305, 3, 25.5, 10, 0, 'South', 'Debit Card', 503.0, 68.85]
], dtype=object)

# For numerical operations, we'll often need to cast columns.
# Example: quantities_np = data_array[:, 3].astype(int)
#          total_sales_np = data_array[:, 10].astype(float)

In [2]:
 data_array.shape

(20, 11)

In [3]:
data_array.dtype

dtype('O')

In [4]:
quantities = data_array[:, 3].astype(int); np.sum(quantities)

np.int64(54)

In [5]:
total_sales = data_array[:, 10].astype(float); np.mean(total_sales)

np.float64(55.0895)

In [6]:
data_array[0, 7]

'West'

In [7]:
data_array[:, 8].size

20

In [8]:
data_array[0]

array([1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.0],
      dtype=object)

In [9]:
type(data_array[0, 9])

float

In [10]:
transaction_ids = data_array[:, 0].astype(int); np.all(transaction_ids == data_array[:, 0])

np.True_

In [13]:
numerical_data = data_array[:, [0,1,2,3,4,5,6,10]].astype(float)

In [14]:
np.max(data_array[:, 3].astype(int))

np.int64(5)

In [15]:
np.min(data_array[:, 4].astype(float))

np.float64(7.25)

In [16]:
np.sum(data_array[:, 5].astype(int))

np.int64(95)

In [17]:
np.median(data_array[:, 10].astype(float))

np.float64(23.625)

In [18]:
np.std(data_array[:, 4].astype(float))

np.float64(14.49983124039725)

In [19]:
len(np.unique(data_array[:, 1].astype(int)))

8

In [20]:
len(np.unique(data_array[:, 2].astype(int)))

8

In [21]:
discounts = data_array[:, 5].astype(int); quantities = data_array[:, 3].astype(int); np.sum(quantities[discounts == 0])

np.int64(18)

In [22]:
quantities = data_array[:, 3].astype(int); total_sales = data_array[:, 10].astype(float); np.mean(total_sales[quantities > 3])

np.float64(138.706)

In [23]:
quantities = data_array[:, 3].astype(int); unit_prices = data_array[:, 4].astype(float); np.sum(quantities * unit_prices)

np.float64(1163.98)

In [24]:
store_locations = data_array[:, 7]; total_sales = data_array[:, 10].astype(float); np.sum(total_sales[store_locations == 'Online'])

np.float64(350.37)

In [25]:
payment_types = data_array[:, 8]; np.sum(payment_types == 'PayPal')

np.int64(6)

In [26]:
salespersons = data_array[:, 9]; discounts = data_array[:, 5].astype(int); np.mean(discounts[salespersons == 501.0])

np.float64(3.75)

In [27]:
salespersons = data_array[:, 9]; np.sum(~(salespersons == np.nan))

np.int64(20)

In [28]:
np.min(data_array[:, 6].astype(int))

np.int64(0)

In [29]:
product_ids = data_array[:, 2].astype(int); transaction_ids = data_array[:, 0].astype(int); transaction_ids[product_ids == 301]

array([1003, 1012, 1016])

In [30]:
store_locations = data_array[:, 7]; total_sales = data_array[:, 10].astype(float); total_sales[store_locations == 'West']

array([17.  , 13.05, 89.98, 10.44, 10.99, 20.88])

In [31]:
store_locations = data_array[:, 7]; quantities = data_array[:, 3].astype(int); np.sum((store_locations == 'Online') & (quantities == 5))

np.int64(2)

In [32]:
payment_types = data_array[:, 8]; total_sales = data_array[:, 10].astype(float); customer_ids = data_array[:, 1].astype(int); customer_ids[(payment_types == 'Credit Card') & (total_sales > 50)]

array([204, 208, 202])

In [33]:
discounts = data_array[:, 5].astype(int); data_array[discounts == 10, :]

array([[1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
       [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0,
        45.9],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78],
       [1020, 206, 305, 3, 25.5, 10, 0, 'South', 'Debit Card', 503.0,
        68.85]], dtype=object)

In [34]:
product_ids = data_array[:, 2].astype(int); store_locations = data_array[:, 7]; unit_prices = data_array[:, 4].astype(float); unit_prices[(product_ids == 307) & (store_locations == 'West')]

array([8.5 , 7.25])

In [35]:
salespersons = data_array[:, 9]; np.sum(salespersons == np.nan)

np.int64(0)

In [36]:
discounts = data_array[:, 5].astype(int); total_sales = data_array[:, 10].astype(float); total_sales[discounts == 0]

array([ 17.  ,  12.75,  21.75, 127.5 ,  25.5 ,  25.5 ,  10.99])

In [37]:
quantities = data_array[:, 3].astype(int); transaction_ids = data_array[:, 0].astype(int); transaction_ids[(quantities == 1) | (quantities == 5)]

array([1003, 1006, 1008, 1009, 1012, 1014, 1015, 1018])

In [38]:
store_locations = data_array[:, 7]; np.sum(np.isin(store_locations, ['North', 'South']))

np.int64(8)

In [39]:
payment_types = data_array[:, 8]; data_array[payment_types != 'Cash', :]

array([[1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.0],
       [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
       [1007, 206, 302, 3, 7.25, 0, 1, 'Online', 'PayPal', nan, 21.75],
       [1008, 206, 308, 1, 10.99, 5, 8, 'West', 'Credit Card', 503.0,
        10.44],
       [1009, 204, 304, 5, 25.5, 0, 6, 'South', 'Credit Card', 501.0,
        127.5],
       [1010, 210, 302, 3, 8.5, 0, 4, 'North', 'Debit Card', 503.0, 25.5],
       [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.5],
       [1012, 205, 301, 1, 10.99, 0, 1, 'West', 'Debit Card', 503.0,
        10.99],
       [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0,
        45.9],
       [1015, 208, 303, 5, 49.99, 5, 4, 'Online', 'Credit Card', nan,
        237.41],
       [1016, 207, 301, 2, 10.99, 5, 5, 'West', 

In [40]:
total_sales = data_array[:, 10].astype(float); product_ids = data_array[:, 2].astype(int); product_ids[(total_sales >= 10) & (total_sales <= 20)]

array([307, 307, 308, 308, 301, 304, 303, 304])

In [41]:
salespersons = data_array[:, 9]; discounts = data_array[:, 5].astype(int); np.sum((salespersons == 503.0) & (discounts > 0))

np.int64(4)

In [42]:
transaction_days = data_array[:, 6].astype(int); data_array[transaction_days == 0, :]

array([[1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1006, 208, 308, 1, 12.75, 0, 0, 'East', 'Cash', 502.0, 12.75],
       [1020, 206, 305, 3, 25.5, 10, 0, 'South', 'Debit Card', 503.0,
        68.85]], dtype=object)

In [43]:
store_locations = data_array[:, 7]; east_indices = (store_locations == 'East'); data_array[east_indices][:, [0, 10]]

array([[1006, 12.75],
       [1014, 12.11]], dtype=object)

In [44]:
product_ids = data_array[:, 2].astype(int); quantities = data_array[:, 3].astype(int); np.sum((product_ids == 304) & (quantities == 1))

np.int64(1)

In [45]:
customer_ids = data_array[:, 1].astype(int); payment_types = data_array[:, 8]; total_sales = data_array[:, 10].astype(float); total_sales[(customer_ids == 206) & (payment_types == 'Cash')]

array([41.75])

In [46]:
np.unique(data_array[:, 7])

array(['East', 'North', 'Online', 'South', 'West'], dtype=object)

In [47]:
unit_prices = data_array[:, 4].astype(float); data_array[np.isclose(unit_prices, 10.99), :]

array([[1002, 206, 305, 4, 10.99, 5, 6, 'Online', 'Cash', nan, 41.75],
       [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1008, 206, 308, 1, 10.99, 5, 8, 'West', 'Credit Card', 503.0,
        10.44],
       [1012, 205, 301, 1, 10.99, 0, 1, 'West', 'Debit Card', 503.0,
        10.99],
       [1016, 207, 301, 2, 10.99, 5, 5, 'West', 'Credit Card', 503.0,
        20.88],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78]],
      dtype=object)

In [48]:
salespersons = data_array[:, 9]; data_array[np.isin(salespersons, [501.0, 502.0]), :]

array([[1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
       [1006, 208, 308, 1, 12.75, 0, 0, 'East', 'Cash', 502.0, 12.75],
       [1009, 204, 304, 5, 25.5, 0, 6, 'South', 'Credit Card', 501.0,
        127.5],
       [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.5],
       [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0,
        45.9],
       [1014, 202, 304, 1, 12.75, 5, 5, 'East', 'Cash', 501.0, 12.11],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78],
       [1019, 208, 304, 2, 7.25, 5, 7, 'South', 'Debit Card', 502.0,
        13.78]], dtype=object)

In [49]:
data_array[:, 4].astype(float) * data_array[:, 3].astype(int)

array([ 17.  ,  43.96,  54.95,  14.5 ,  99.98,  12.75,  21.75,  10.99,
       127.5 ,  25.5 ,  25.5 ,  10.99,  51.  ,  12.75, 249.95,  21.98,
        21.98, 249.95,  14.5 ,  76.5 ])

In [ ]:
(data_array[:, 4].astype(float) * data_array[:, 3].astype(int) * data_array[:, 5].astype(int)) / 100.0

In [50]:
data_array[:, 10].astype(float) > 75

array([False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False,  True, False, False,  True,
       False, False])

In [51]:
data_array[:, 10].astype(float) * 1.05

array([ 17.85  ,  43.8375,  51.933 ,  13.7025,  94.479 ,  13.3875,
        22.8375,  10.962 , 133.875 ,  26.775 ,  26.775 ,  11.5395,
        48.195 ,  12.7155, 249.2805,  21.924 ,  20.769 , 249.2805,
        14.469 ,  72.2925])

In [52]:
np.where(data_array[:, 10].astype(float) > 100, 1, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [53]:
total_sales = data_array[:, 10].astype(float); quantities = data_array[:, 3].astype(int); np.divide(total_sales, quantities, out=np.zeros_like(total_sales), where=quantities!=0)

array([ 8.5   , 10.4375,  9.892 ,  6.525 , 44.99  , 12.75  ,  7.25  ,
       10.44  , 25.5   ,  8.5   ,  8.5   , 10.99  , 22.95  , 12.11  ,
       47.482 , 10.44  ,  9.89  , 47.482 ,  6.89  , 22.95  ])

In [54]:
(data_array[:, 4].astype(float) * data_array[:, 3].astype(int)) - data_array[:, 10].astype(float)

array([ 0.  ,  2.21,  5.49,  1.45, 10.  ,  0.  ,  0.  ,  0.55,  0.  ,
        0.  ,  0.  ,  0.  ,  5.1 ,  0.64, 12.54,  1.1 ,  2.2 , 12.54,
        0.72,  7.65])

In [55]:
data_array[:, 3].astype(int) + 5

array([ 7,  9, 10,  7,  7,  6,  8,  6, 10,  8,  8,  6,  7,  6, 10,  7,  7,
       10,  7,  8])

In [56]:
unit_prices = data_array[:, 4].astype(float); (unit_prices - np.mean(unit_prices)) / np.std(unit_prices)

array([-0.67297335, -0.50124721, -0.50124721, -0.75918125,  2.18843926,
       -0.37986649, -0.75918125, -0.50124721,  0.49945409, -0.67297335,
       -0.67297335, -0.50124721,  0.49945409, -0.37986649,  2.18843926,
       -0.50124721, -0.50124721,  2.18843926, -0.75918125,  0.49945409])

In [57]:
np.where(data_array[:, 5].astype(int) > 0, 1, 0)

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [58]:
online_sales_indices = (data_array[:, 7] == 'Online'); online_total_sales = data_array[online_sales_indices, 10].astype(float); online_total_sales * 0.98

array([ 40.915 ,  48.4708,  21.315 , 232.6618])

In [61]:
total_sales = data_array[:, 10].astype(float); quantities = data_array[:, 3].astype(int); np.divide(total_sales, quantities, out=np.zeros_like(total_sales), where=quantities!=0)

array([ 8.5   , 10.4375,  9.892 ,  6.525 , 44.99  , 12.75  ,  7.25  ,
       10.44  , 25.5   ,  8.5   ,  8.5   , 10.99  , 22.95  , 12.11  ,
       47.482 , 10.44  ,  9.89  , 47.482 ,  6.89  , 22.95  ])

In [62]:
salespersons_float = data_array[:, 9].astype(float); np.where(np.isnan(salespersons_float), -1.0, salespersons_float)

array([503.,  -1.,  -1., 501., 502., 502.,  -1., 503., 501., 503., 501.,
       503., 502., 501.,  -1., 503., 502., 503., 502., 503.])

In [63]:
data_array[:, 6].astype(int) % 3

array([1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 0])

In [64]:
total_sales = data_array[:, 10].astype(float); transaction_ids = data_array[:, 0].astype(int); transaction_ids[np.argsort(total_sales)]

array([1008, 1012, 1014, 1006, 1004, 1019, 1001, 1017, 1016, 1007, 1011,
       1010, 1002, 1013, 1003, 1020, 1005, 1009, 1015, 1018])

In [65]:
np.sort(data_array[:, 3].astype(int))[-3:]

array([5, 5, 5])

In [66]:
total_sales = data_array[:, 10].astype(float); data_array[np.argmax(total_sales), 7]

'Online'

In [67]:
np.sort(np.unique(data_array[:, 8].astype(str)))

array(['Cash', 'Credit Card', 'Debit Card', 'PayPal'], dtype='<U11')

In [68]:
customer_ids = data_array[:, 1].astype(int); data_array[np.argsort(customer_ids)]

array([[1014, 202, 304, 1, 12.75, 5, 5, 'East', 'Cash', 501.0, 12.11],
       [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.5],
       [1018, 202, 302, 5, 49.99, 5, 8, 'North', 'Credit Card', 503.0,
        237.41],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78],
       [1009, 204, 304, 5, 25.5, 0, 6, 'South', 'Credit Card', 501.0,
        127.5],
       [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1012, 205, 301, 1, 10.99, 0, 1, 'West', 'Debit Card', 503.0,
        10.99],
       [1002, 206, 305, 4, 10.99, 5, 6, 'Online', 'Cash', nan, 41.75],
       [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0,
        45.9],
       [1007, 206, 302, 3, 7.25, 0, 1, 'Online', 'PayPal', nan, 21.75],
       [1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1008, 206, 308, 1, 10.99, 5, 8, 'West', 'Credit Card', 503.0,
        10.44],
       [1020, 206, 305, 3, 25.5, 10, 0, 'South', 

In [69]:
unit_prices = data_array[:, 4].astype(float); transaction_ids = data_array[:, 0].astype(int); transaction_ids[np.argsort(unit_prices)[:5]]

array([1004, 1007, 1019, 1001, 1011])

In [70]:
discounts = data_array[:, 5].astype(int); salespersons = data_array[:, 9]; non_zero_discount_indices = (discounts > 0); salespersons[non_zero_discount_indices][np.argmin(discounts[non_zero_discount_indices])]

nan

In [71]:
store_locations = data_array[:, 7].astype(str); total_sales = data_array[:, 10].astype(float); total_sales[np.argsort(store_locations)]

array([ 12.75,  12.11,  25.5 , 237.41,  19.78,  45.9 ,  25.5 ,  41.75,
        49.46,  21.75, 237.41,  68.85,  13.78, 127.5 ,  10.44,  20.88,
        89.98,  13.05,  10.99,  17.  ])

In [72]:
total_sales = data_array[:, 10].astype(float); product_ids = data_array[:, 2].astype(int); sorted_indices = np.argsort(total_sales); median_index_in_sorted = (len(total_sales) - 1) // 2; product_ids[sorted_indices[median_index_in_sorted]]

np.int64(302)

In [73]:
product_ids = data_array[:, 2].astype(int); _, idx = np.unique(product_ids, return_index=True); product_ids[np.sort(idx)]

array([307, 305, 301, 306, 308, 302, 304, 303])

In [74]:
# Pure NumPy way
unique_locs = np.unique(data_array[:, 7].astype(str))
sum_sales_per_loc = {loc: np.sum(data_array[data_array[:, 7] == loc, 10].astype(float)) for loc in unique_locs}
# sum_sales_per_loc will be a dict

In [84]:
unique_locs

array(['East', 'North', 'Online', 'South', 'West'], dtype='<U6')

In [76]:
unique_pays, counts = np.unique(data_array[:, 8].astype(str), return_counts=True)
# dict(zip(unique_pays, counts))

In [83]:
unique_pays, counts

(array(['Cash', 'Credit Card', 'Debit Card', 'PayPal'], dtype='<U11'),
 array([3, 7, 4, 6]))

In [78]:
salespersons_float = data_array[:, 9].astype(float)
valid_sp_indices = ~np.isnan(salespersons_float)
unique_sps = np.unique(salespersons_float[valid_sp_indices])
avg_disc_per_sp = {sp: np.mean(data_array[(salespersons_float == sp) & valid_sp_indices, 5].astype(int)) for sp in unique_sps}
# avg_disc_per_sp

In [82]:
salespersons_float

array([503.,  nan,  nan, 501., 502., 502.,  nan, 503., 501., 503., 501.,
       503., 502., 501.,  nan, 503., 502., 503., 502., 503.])

In [79]:
unique_prods = np.unique(data_array[:, 2].astype(int))
max_qty_per_prod = {prod: np.max(data_array[data_array[:, 2].astype(int) == prod, 3].astype(int)) for prod in unique_prods}
# max_qty_per_prod

In [81]:
unique_prods

array([301, 302, 303, 304, 305, 306, 307, 308])

In [80]:
unique_days = np.unique(data_array[:, 6].astype(int))
qty_per_day = {day: np.sum(data_array[data_array[:, 6].astype(int) == day, 3].astype(int)) for day in unique_days}
# qty_per_day

In [85]:
unique_days

array([0, 1, 4, 5, 6, 7, 8])

In [87]:
paypal_transactions = data_array[data_array[:, 8] == 'PayPal', :]

In [88]:
paypal_transactions

array([[1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.0],
       [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
       [1007, 206, 302, 3, 7.25, 0, 1, 'Online', 'PayPal', nan, 21.75],
       [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.5],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78]],
      dtype=object)

In [89]:
product_ids = data_array[:, 2].astype(int); total_sales = data_array[:, 10].astype(float); np.mean(total_sales[product_ids == 301])

np.float64(27.11)

In [90]:
np.sum((data_array[:, 7] == 'Online') & (data_array[:, 8] == 'Credit Card'))

np.int64(1)

In [ ]:
unique_cust = np.unique(data_array[:, 1].astype(int))
total_disc_per_cust = {cust: np.sum(data_array[data_array[:, 1].astype(int) == cust, 5].astype(int)) for cust in unique_cust}
# total_disc_per_cust

In [92]:
payment_types = data_array[:, 8]; unit_prices = data_array[:, 4].astype(float); np.min(unit_prices[payment_types == 'Cash'])

np.float64(10.99)

In [93]:
salespersons = data_array[:, 9]; quantities = data_array[:, 3].astype(int); np.sum(quantities[salespersons == 502.0])

np.int64(9)

In [94]:
unique_prods = np.unique(data_array[:, 2].astype(int))
avg_sale_per_prod = {prod: np.mean(data_array[data_array[:, 2].astype(int) == prod, 10].astype(float)) for prod in unique_prods}
# avg_sale_per_prod

In [95]:
unique_prods

array([301, 302, 303, 304, 305, 306, 307, 308])

In [96]:
unique_pays = np.unique(data_array[:, 8].astype(str))
avg_sales = np.array([np.mean(data_array[data_array[:, 8] == pay, 10].astype(float)) for pay in unique_pays])
# unique_pays[np.argmax(avg_sales)]

In [97]:
unique_pays

array(['Cash', 'Credit Card', 'Debit Card', 'PayPal'], dtype='<U11')

In [98]:
np.corrcoef(data_array[:, 3].astype(int), data_array[:, 10].astype(float))[0, 1]

np.float64(0.7301544743648399)

In [99]:
total_sales = data_array[:, 10].astype(float); mean_ts = np.mean(total_sales); std_ts = np.std(total_sales); np.sum(total_sales > (mean_ts + 2 * std_ts))

np.int64(2)

In [100]:
np.where(data_array[:, 5].astype(int) > 0, "Discounted", "No Discount")

array(['No Discount', 'Discounted', 'Discounted', 'Discounted',
       'Discounted', 'No Discount', 'No Discount', 'Discounted',
       'No Discount', 'No Discount', 'No Discount', 'No Discount',
       'Discounted', 'Discounted', 'Discounted', 'Discounted',
       'Discounted', 'Discounted', 'Discounted', 'Discounted'],
      dtype='<U11')

In [102]:
np.percentile(data_array[:, 4].astype(float), 75)

np.float64(25.5)

In [103]:
quantities = data_array[:, 3].astype(int); discounts = data_array[:, 5].astype(int); avg_qty = np.mean(quantities); np.mean(discounts[quantities > avg_qty])

np.float64(3.888888888888889)

In [104]:
total_sales = data_array[:, 10].astype(float); store_locations = data_array[:, 7]; (np.sum(total_sales[store_locations == 'West']) / np.sum(total_sales)) * 100

np.float64(14.734205247823997)

In [105]:
customer_product_pairs = np.column_stack((data_array[:, 1].astype(int), data_array[:, 2].astype(int))); len(np.unique(customer_product_pairs, axis=0))

17

In [106]:
total_sales = data_array[:, 10].astype(float); p10 = np.percentile(total_sales, 10); p90 = np.percentile(total_sales, 90); transaction_ids = data_array[:, 0].astype(int); transaction_ids[(total_sales > p10) & (total_sales < p90)]

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1010, 1011, 1013,
       1014, 1016, 1017, 1019, 1020])

In [107]:
salespersons = data_array[:, 9]; store_locations = data_array[:, 7]; quantities = data_array[:, 3].astype(int); np.sum(quantities[(salespersons == 503.0) & (store_locations == 'North')])

np.int64(8)

In [109]:
total_sales = data_array[:, 10].astype(float); ranks = np.empty_like(total_sales, dtype=int); ranks[np.argsort(np.argsort(total_sales))] = np.arange(len(total_sales)) + 1; ranks_col_only = ranks.reshape(-1,1); # To replace in a copy: new_array = data_array.copy(); new_array[:, 10] = ranks

In [113]:
total_sales

array([ 17.  ,  41.75,  49.46,  13.05,  89.98,  12.75,  21.75,  10.44,
       127.5 ,  25.5 ,  25.5 ,  10.99,  45.9 ,  12.11, 237.41,  20.88,
        19.78, 237.41,  13.78,  68.85])

In [110]:
transaction_days = data_array[:, 6].astype(int); total_sales = data_array[:, 10].astype(float); np.sum(total_sales[np.isin(transaction_days, [0, 1, 2])])

np.float64(198.79)

In [111]:
west_payments = data_array[data_array[:, 7] == 'West', 8].astype(str)

In [112]:
west_payments

array(['PayPal', 'Credit Card', 'PayPal', 'Credit Card', 'Debit Card',
       'Credit Card'], dtype='<U11')

In [114]:
total_sales = data_array[:, 10].astype(float); np.sum(np.isclose(total_sales, np.round(total_sales)))

np.int64(1)

In [115]:
np.average(data_array[:, 5].astype(int), weights=data_array[:, 3].astype(int))

np.float64(4.814814814814815)

In [116]:
salespersons = data_array[:, 9]; store_locations = data_array[:, 7]; transaction_ids = data_array[:, 0].astype(int); nan_salesperson_indices = np.array([x is np.nan for x in salespersons]); transaction_ids[nan_salesperson_indices & (store_locations == 'Online')]

array([1002, 1003, 1007, 1015])