In [1]:
import numpy as np

In [2]:
data=np.random.randint(0,10,5)

In [3]:
data

array([2, 8, 9, 7, 7])

In [4]:
data+3

array([ 5, 11, 12, 10, 10])

In [6]:
x=np.random.randint(0,10,(4,3))

In [7]:
x

array([[4, 5, 6],
       [4, 8, 9],
       [6, 2, 3],
       [7, 8, 6]])

In [8]:
y=np.random.randint(0,10,(1,3))

In [9]:
x

array([[4, 5, 6],
       [4, 8, 9],
       [6, 2, 3],
       [7, 8, 6]])

In [ ]:
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]

In [10]:
y

array([[4, 7, 4]])

In [11]:
x+y

array([[ 8, 12, 10],
       [ 8, 15, 13],
       [10,  9,  7],
       [11, 15, 10]])

In [12]:
x=np.random.randint(0,10,(4,1))

In [13]:
x

array([[7],
       [8],
       [4],
       [8]])

In [14]:
y=np.random.randint(0,10,4)

In [15]:
x

array([[7],
       [8],
       [4],
       [8]])

In [16]:
y

array([6, 6, 3, 4])

In [ ]:
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]

In [ ]:
5555
1111
1111
5555

In [17]:
x+y

array([[13, 13, 10, 11],
       [14, 14, 11, 12],
       [10, 10,  7,  8],
       [14, 14, 11, 12]])

In [18]:
x

array([[7],
       [8],
       [4],
       [8]])

In [19]:
y

array([6, 6, 3, 4])

In [ ]:
### Link :https://numpy.org/devdocs//user/basics.broadcasting.html

In [20]:
import numpy as np

In [ ]:
data([12., 45., 78., 23., 56.],
       [34., 67., 89., 12., 90.],
       [56., 21., 43., 65., 87.],
       [78., 34., 12., 89., 23.],
       [90., 11., 67., 32., 45.],
       [14., 58., 29., 71., 63.],
       [32., 84., 91., 17., 55.],
       [46., 38., 27., 66., 49.],
       [53., 72., 19., 88., 30.],
       [61., 40., 76., 35., 20])

In [22]:
data.shape

(5,)

In [23]:
import glob

In [24]:
x=2
x**2

4

In [25]:
[4,2,3,4]

[4, 2, 3, 4]

In [26]:
x=2
x**2
for i in [4,2,3,4]:
  print(i**2)

16
4
9
16


In [30]:
data=np.loadtxt("/content/sample_data/sample.text")
paths=glob.glob("/content/*.txt")

In [31]:
paths

[]

In [33]:
for i in paths:
  data=np.loadtxt(i)
  print(data)
  print(" ")

In [37]:
data=np.random.randint(0,10,5)

In [38]:
data

array([1, 7, 9, 9, 8])

In [39]:
data.cumsum()

array([ 1,  8, 17, 26, 34])

In [40]:
data.cumprod()

array([   1,    7,   63,  567, 4536])

In [41]:
data=np.random.randint(0,10,(3,3))

In [42]:
data

array([[5, 4, 0],
       [3, 1, 7],
       [7, 6, 9]])

In [43]:
data.cumsum(axis=1)

array([[ 5,  9,  9],
       [ 3,  4, 11],
       [ 7, 13, 22]])

In [44]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
a=np.random.choice([10,20,30,40,50],size=3)
a

array([30, 40, 50])

In [47]:
a=np.random.choice([10,20,30,40,50],size=3,replace=True)
a

array([40, 10, 50])

In [48]:
a=np.random.choice([10,20,30,40,50],size=3,replace=False)
a

array([30, 40, 50])